---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # copy files/system/* into the image root (e.g. configs, udev rules, etc.)
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
    install:
      packages:
        # shell
        - zsh
        # terminal multiplexer
        - tmux
        # dotfile manager
        - chezmoi
        # rootless containers / distros
        - distrobox

  - type: signing # sets up policy & signing files for signed images
